[package]
authors = ["Jason Ozias <jason.g.ozias@gmail.com>"]
categories = ["development-tools", "development-tools::build-utils"]
description = "Generate 'cargo:rustc-env' instructions via 'build.rs' for use in your code via the env! macro"
documentation = "https://docs.rs/vergen"
edition = "2021"
homepage = "https://github.com/rustyhorde/vergen"
keywords = ["cargo", "instructions", "build", "tool"]
license = "MIT OR Apache-2.0"
name = "vergen"
readme = "README.md"
repository = "https://github.com/rustyhorde/vergen"
resolver = "2"
version = "7.5.0"

[package.metadata.cargo-all-features]
denylist = ["local_offset","time","git2","rustc_version","sysinfo"]

[features]
default = ["build", "cargo", "git", "rustc", "si"]
build = ["time"]
cargo = []
git = ["time", "git2"]
rustc = ["rustc_version"]
si = ["sysinfo"]
local_offset = ["time/local-offset"]

[dependencies]
anyhow = "1.0.69"
cfg-if = "1.0.0"
enum-iterator = "1.2.0"
getset = "0.1.2"
git2 = { version = "0.16.1", optional = true, default-features = false }
rustc_version = { version = "0.4.0", optional = true }
sysinfo = { version = "0.27.7", optional = true, default-features = false }
thiserror = "1.0.38"
time = { version = "0.3.17", features = ["formatting"], optional = true }

[build-dependencies]
anyhow = "1.0.69"
time = { version = "0.3.17", features = ["formatting"] }
rustversion = "1.0.11"

[dev-dependencies]
lazy_static = "1.4.0"
regex = "1.7.1"
serial_test = "1.0.0"
tempfile = "3.3.0"

